| test.py:10:11:10:47 | test.py:10 | MyException() | exception.kind |
| test.py:15:25:15:25 | test.py:15 | e | exception.kind |
| test.py:16:13:16:34 | test.py:16 | Attribute() | exception.info |
| test.py:17:15:17:15 | test.py:17 | s | exception.info |
| test.py:19:13:19:36 | test.py:19 | Attribute() | [exception.info] |
| test.py:20:13:20:37 | test.py:20 | Attribute() | [exception.info] |
| test.py:21:13:21:36 | test.py:21 | Attribute() | [exception.info] |
| test.py:21:35:21:35 | test.py:21 | t | [exception.info] |
| test.py:22:13:22:58 | test.py:22 | Attribute() | [exception.info] |
| test.py:23:13:23:57 | test.py:23 | Attribute() | [exception.info] |
| test.py:24:13:24:35 | test.py:24 | Attribute() | [exception.info] |
| test.py:25:13:25:36 | test.py:25 | Attribute() | [exception.info] |
| test.py:26:25:26:25 | test.py:26 | e | exception.kind |
| test.py:26:25:26:33 | test.py:26 | Attribute | exception.info |
| test.py:26:25:26:41 | test.py:26 | Tuple | [[exception.info]] |
| test.py:26:25:26:41 | test.py:26 | Tuple | [exception.info] |
| test.py:26:36:26:36 | test.py:26 | e | exception.kind |
| test.py:26:36:26:41 | test.py:26 | Attribute | [exception.info] |
| test.py:27:19:27:19 | test.py:27 | t | [exception.info] |
| test.py:27:22:27:22 | test.py:27 | u | [exception.info] |
| test.py:27:25:27:25 | test.py:27 | v | [exception.info] |
| test.py:27:28:27:28 | test.py:27 | w | [exception.info] |
| test.py:27:31:27:31 | test.py:27 | x | [exception.info] |
| test.py:27:34:27:34 | test.py:27 | y | [exception.info] |
| test.py:27:37:27:37 | test.py:27 | z | [exception.info] |
| test.py:27:40:27:46 | test.py:27 | message | exception.info |
| test.py:27:49:27:52 | test.py:27 | args | [exception.info] |
