// Generated automatically from javax.jdo.JDOException for testing purposes

package javax.jdo;

import java.io.PrintStream;
import java.io.PrintWriter;

public class JDOException extends RuntimeException
{
    public JDOException(){}
    public JDOException(String p0){}
    public JDOException(String p0, Object p1){}
    public JDOException(String p0, Throwable p1){}
    public JDOException(String p0, Throwable p1, Object p2){}
    public JDOException(String p0, Throwable[] p1){}
    public JDOException(String p0, Throwable[] p1, Object p2){}
    public Object getFailedObject(){ return null; }
    public String toString(){ return null; }
    public Throwable getCause(){ return null; }
    public Throwable initCause(Throwable p0){ return null; }
    public Throwable[] getNestedExceptions(){ return null; }
    public void printStackTrace(){}
    public void printStackTrace(PrintStream p0){}
    public void printStackTrace(PrintWriter p0){}
}
